#!/bin/bash

# Automated deployment script for SuiAudit
# This script publishes the contract, creates service, and saves configuration

set -e  # Exit on error

echo "🚀 Starting SuiAudit deployment..."

# Step 1: Publish contract
echo "📦 Publishing contract..."
PUBLISH_OUTPUT=$(sui client publish --gas-budget 100000000 --json 2>&1)
echo "$PUBLISH_OUTPUT" > publish_output.json

# Extract package ID
PACKAGE_ID=$(echo "$PUBLISH_OUTPUT" | jq -r '.objectChanges[] | select(.type == "published") | .packageId')
echo "✅ Package published: $PACKAGE_ID"

# Step 2: Create service
echo "🔧 Creating SuiAudit service..."
SETUP_OUTPUT=$(sui client call \
  --package "$PACKAGE_ID" \
  --module main \
  --function setup_suiaudit_service \
  --gas-budget 100000000 \
  --json 2>&1)

echo "$SETUP_OUTPUT" > setup_output.json

# Extract Service ID (it's a shared object)
SERVICE_ID=$(echo "$SETUP_OUTPUT" | jq -r '.objectChanges[] | select(.objectType | contains("::subscription::Service")) | .objectId')
echo "✅ Service created: $SERVICE_ID"

# Extract Cap ID (owned by sender)
CAP_ID=$(echo "$SETUP_OUTPUT" | jq -r '.objectChanges[] | select(.objectType | contains("::subscription::Cap")) | .objectId')
echo "✅ Cap created: $CAP_ID"

# Step 3: Generate frontend config
echo "📝 Generating configuration files..."

# TypeScript config
cat > frontend_config.ts << EOF
// Auto-generated by deploy_and_setup.sh
// DO NOT EDIT MANUALLY

export const SUIAUDIT_CONTRACT = {
  packageId: "${PACKAGE_ID}",
  serviceId: "${SERVICE_ID}",
  capId: "${CAP_ID}",
  clockId: "0x6",
  network: "testnet",
  deployedAt: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} as const;
EOF

# JSON config
cat > frontend_config.json << EOF
{
  "packageId": "${PACKAGE_ID}",
  "serviceId": "${SERVICE_ID}",
  "capId": "${CAP_ID}",
  "clockId": "0x6",
  "network": "testnet",
  "deployedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF

# .env format
cat > .env.suiaudit << EOF
VITE_SUIAUDIT_PACKAGE_ID=${PACKAGE_ID}
VITE_SUIAUDIT_SERVICE_ID=${SERVICE_ID}
VITE_SUIAUDIT_CAP_ID=${CAP_ID}
VITE_SUIAUDIT_CLOCK_ID=0x6
VITE_SUIAUDIT_NETWORK=testnet
EOF

echo "✅ Configuration files generated:"
echo "   - frontend_config.ts (TypeScript)"
echo "   - frontend_config.json (JSON)"
echo "   - .env.suiaudit (Environment variables)"
echo ""
echo "📋 Summary:"
echo "   Package ID: $PACKAGE_ID"
echo "   Service ID: $SERVICE_ID"
echo "   Cap ID:     $CAP_ID"
echo ""
echo "🎉 Deployment complete! Copy the config file to your frontend project."
